import os
from pathlib import Path

from agentsphere.interfaces.api.app import create_app


def generate_typescript_interfaces() -> None:
    """Instantiates our FastAPI app, extracts its OpenAPI schema dict, and automatically compiles

    and writes pristine TypeScript definitions to the Next.js project folder.
    """
    app = create_app()
    schema = app.openapi()

    web_types_dir = Path(__file__).resolve().parents[3] / "web" / "types"
    os.makedirs(web_types_dir, exist_ok=True)

    # 1. Output dynamic schemas and models mapping dictionaries
    components = schema.get("components", {})
    schemas = components.get("schemas", {})

    ts_schemas_lines = [
        "/* eslint-disable @typescript-eslint/no-explicit-any */",
        "// Autogenerated from FastAPI OpenAPI schema. Do NOT manually edit.",
        "",
    ]
    ts_models_lines = [
        "/* eslint-disable @typescript-eslint/no-explicit-any */",
        "// Autogenerated DB Models from FastAPI OpenAPI schema.",
        "",
    ]

    for name, s_def in schemas.items():
        properties = s_def.get("properties", {})
        required_fields = s_def.get("required", [])

        lines = [f"export interface {name} {{"]
        for prop_name, p_def in properties.items():
            is_req = prop_name in required_fields
            opt = "" if is_req else "?"

            p_type = p_def.get("type", "any")
            ts_type = "any"

            if p_type == "string":
                ts_type = "string"
            elif p_type in ("integer", "number"):
                ts_type = "number"
            elif p_type == "boolean":
                ts_type = "boolean"
            elif p_type == "array":
                items_def = p_def.get("items", {})
                ref_type = items_def.get("$ref", "")
                if ref_type:
                    ts_type = f"{ref_type.split('/')[-1]}[]"
                else:
                    ts_type = "any[]"
            elif "$ref" in p_def:
                ts_type = p_def["$ref"].split("/")[-1]

            lines.append(f"  {prop_name}{opt}: {ts_type};")
        lines.append("}")
        lines.append("")

        if "Model" in name or name in ("Tenant", "User", "ApiKey", "Conversation", "KnowledgeBase"):
            ts_models_lines.extend(lines)
        else:
            ts_schemas_lines.extend(lines)

    # 2. Write schemas types
    with open(web_types_dir / "schemas.ts", "w", encoding="utf-8") as f:
        f.write("\n".join(ts_schemas_lines))
    print(f"Wrote autogenerated schemas typings to {web_types_dir / 'schemas.ts'}")

    # 3. Write models types
    with open(web_types_dir / "models.ts", "w", encoding="utf-8") as f:
        f.write("\n".join(ts_models_lines))
    print(f"Wrote autogenerated models typings to {web_types_dir / 'models.ts'}")

    # 4. Write generic API endpoints contract definitions
    api_lines = [
        "// Autogenerated Frontend API Endpoints. Do NOT manually edit.",
        'import { AgentDefinition, RuntimeRequest, RuntimeResponse } from "./schemas";',
        "",
        "export interface APIEndpoints {",
        "  '/api/v1/auth/login': { method: 'POST', body: any, response: any };",
        "  '/api/v1/tenants': { method: 'POST', body: any, response: any };",
        "  '/api/v1/conversations': { method: 'POST', body: any, response: any };",
        "  '/api/v1/knowledge-bases': { method: 'POST', body: any, response: any };",
        "  '/api/v1/agents': { method: 'GET', body: null, response: AgentDefinition[] };",
        "}",
    ]
    with open(web_types_dir / "api.ts", "w", encoding="utf-8") as f:
        f.write("\n".join(api_lines))
    print(f"Wrote API endpoints typings contract to {web_types_dir / 'api.ts'}")


if __name__ == "__main__":
    generate_typescript_interfaces()
