from typing import Any, Protocol

from agentsphere.ai.schemas.inference import PromptMessage


class MemoryStore(Protocol):
    async def get(self, key: str) -> Any: ...

    async def set(self, key: str, value: Any, ttl: int | None = None) -> None: ...

    async def delete(self, key: str) -> None: ...


class ConversationMemory(Protocol):
    async def get_messages(self, conversation_id: str) -> list[PromptMessage]: ...

    async def add_message(self, conversation_id: str, message: PromptMessage) -> None: ...

    async def clear(self, conversation_id: str) -> None: ...

    async def extract_and_store_facts(self, conversation_id: str) -> list[str]: ...
