from typing import Any, Protocol
from uuid import UUID


class TenantRepositoryProtocol(Protocol):
    async def get(self, id: UUID, tenant_id: UUID | None = None) -> dict[str, Any] | None: ...

    async def get_all(
        self, tenant_id: UUID | None = None, **filters: Any
    ) -> list[dict[str, Any]]: ...

    async def create(self, **kwargs: Any) -> dict[str, Any]: ...

    async def update(
        self, id: UUID, tenant_id: UUID | None = None, **kwargs: Any
    ) -> dict[str, Any] | None: ...

    async def delete(self, id: UUID, tenant_id: UUID | None = None) -> bool: ...

    async def exists(self, id: UUID, tenant_id: UUID | None = None) -> bool: ...

    async def get_by_slug(self, slug: str) -> dict[str, Any] | None: ...


class UserRepositoryProtocol(Protocol):
    async def get(self, id: UUID, tenant_id: UUID | None = None) -> dict[str, Any] | None: ...

    async def get_all(
        self, tenant_id: UUID | None = None, **filters: Any
    ) -> list[dict[str, Any]]: ...

    async def create(self, **kwargs: Any) -> dict[str, Any]: ...

    async def update(
        self, id: UUID, tenant_id: UUID | None = None, **kwargs: Any
    ) -> dict[str, Any] | None: ...

    async def delete(self, id: UUID, tenant_id: UUID | None = None) -> bool: ...

    async def exists(self, id: UUID, tenant_id: UUID | None = None) -> bool: ...

    async def get_by_email(self, email: str) -> dict[str, Any] | None: ...

    async def get_by_tenant(self, tenant_id: UUID) -> list[dict[str, Any]]: ...


class ApiKeyRepositoryProtocol(Protocol):
    async def get(self, id: UUID, tenant_id: UUID | None = None) -> dict[str, Any] | None: ...

    async def get_all(
        self, tenant_id: UUID | None = None, **filters: Any
    ) -> list[dict[str, Any]]: ...

    async def create(self, **kwargs: Any) -> dict[str, Any]: ...

    async def update(
        self, id: UUID, tenant_id: UUID | None = None, **kwargs: Any
    ) -> dict[str, Any] | None: ...

    async def delete(self, id: UUID, tenant_id: UUID | None = None) -> bool: ...

    async def exists(self, id: UUID, tenant_id: UUID | None = None) -> bool: ...

    async def get_by_key_hash(self, key_hash: str) -> dict[str, Any] | None: ...
