from typing import Any, Protocol
from uuid import UUID


class TenantRepositoryProtocol(Protocol):
    async def get(self, id: UUID, tenant_id: UUID | None = None) -> dict[str, Any] | None: ...

    async def get_all(
        self, tenant_id: UUID | None = None, **filters: Any
    ) -> list[dict[str, Any]]: ...

    async def create(self, **kwargs: Any) -> dict[str, Any]: ...

    async def update(
        self, id: UUID, tenant_id: UUID | None = None, **kwargs: Any
    ) -> dict[str, Any] | None: ...

    async def delete(self, id: UUID, tenant_id: UUID | None = None) -> bool: ...

    async def exists(self, id: UUID, tenant_id: UUID | None = None) -> bool: ...

    async def get_by_slug(self, slug: str) -> dict[str, Any] | None: ...


class UserRepositoryProtocol(Protocol):
    async def get(self, id: UUID, tenant_id: UUID | None = None) -> dict[str, Any] | None: ...

    async def get_all(
        self, tenant_id: UUID | None = None, **filters: Any
    ) -> list[dict[str, Any]]: ...

    async def create(self, **kwargs: Any) -> dict[str, Any]: ...

    async def update(
        self, id: UUID, tenant_id: UUID | None = None, **kwargs: Any
    ) -> dict[str, Any] | None: ...

    async def delete(self, id: UUID, tenant_id: UUID | None = None) -> bool: ...

    async def exists(self, id: UUID, tenant_id: UUID | None = None) -> bool: ...

    async def get_by_email(self, email: str) -> dict[str, Any] | None: ...

    async def get_by_tenant(self, tenant_id: UUID) -> list[dict[str, Any]]: ...


class ApiKeyRepositoryProtocol(Protocol):
    async def get(self, id: UUID, tenant_id: UUID | None = None) -> dict[str, Any] | None: ...

    async def get_all(
        self, tenant_id: UUID | None = None, **filters: Any
    ) -> list[dict[str, Any]]: ...

    async def create(self, **kwargs: Any) -> dict[str, Any]: ...

    async def update(
        self, id: UUID, tenant_id: UUID | None = None, **kwargs: Any
    ) -> dict[str, Any] | None: ...

    async def delete(self, id: UUID, tenant_id: UUID | None = None) -> bool: ...

    async def exists(self, id: UUID, tenant_id: UUID | None = None) -> bool: ...

    async def get_by_key_hash(self, key_hash: str) -> dict[str, Any] | None: ...


class ConversationRepositoryProtocol(Protocol):
    async def get(self, id: UUID, tenant_id: UUID | None = None) -> dict[str, Any] | None: ...

    async def get_all(
        self, tenant_id: UUID | None = None, **filters: Any
    ) -> list[dict[str, Any]]: ...

    async def create(self, **kwargs: Any) -> dict[str, Any]: ...

    async def update(
        self, id: UUID, tenant_id: UUID | None = None, **kwargs: Any
    ) -> dict[str, Any] | None: ...

    async def delete(self, id: UUID, tenant_id: UUID | None = None) -> bool: ...

    async def exists(self, id: UUID, tenant_id: UUID | None = None) -> bool: ...

    async def add_message(self, conversation_id: UUID, role: str, content: str) -> dict[str, Any]: ...

    async def get_messages(self, conversation_id: UUID) -> list[dict[str, Any]]: ...

    async def add_summary(self, conversation_id: UUID, content: str) -> dict[str, Any]: ...

    async def get_latest_summary(self, conversation_id: UUID) -> dict[str, Any] | None: ...


class KnowledgeRepositoryProtocol(Protocol):
    async def get(self, id: UUID, tenant_id: UUID | None = None) -> dict[str, Any] | None: ...

    async def get_all(
        self, tenant_id: UUID | None = None, **filters: Any
    ) -> list[dict[str, Any]]: ...

    async def create(self, **kwargs: Any) -> dict[str, Any]: ...

    async def update(
        self, id: UUID, tenant_id: UUID | None = None, **kwargs: Any
    ) -> dict[str, Any] | None: ...

    async def delete(self, id: UUID, tenant_id: UUID | None = None) -> bool: ...

    async def exists(self, id: UUID, tenant_id: UUID | None = None) -> bool: ...

    async def create_collection(self, knowledge_base_id: UUID, name: str) -> dict[str, Any]: ...

    async def get_collections(self, knowledge_base_id: UUID) -> list[dict[str, Any]]: ...

    async def create_document(self, collection_id: UUID, name: str, source_type: str, meta_info: dict[str, Any] | None = None) -> dict[str, Any]: ...

    async def get_documents(self, collection_id: UUID) -> list[dict[str, Any]]: ...

    async def add_chunk(self, document_id: UUID, text_content: str, embedding: list[float] | None = None, page_index: int | None = None) -> dict[str, Any]: ...

    async def similarity_search(
        self,
        knowledge_base_id: UUID,
        query_embedding: list[float],
        limit: int = 5,
        similarity_threshold: float = 0.0,
    ) -> list[dict[str, Any]]: ...
