// Autogenerated Frontend API Endpoints. Do NOT manually edit.
import { AgentDefinition, RuntimeRequest, RuntimeResponse } from "./schemas";

export interface APIEndpoints {
  '/api/v1/auth/login': { method: 'POST', body: any, response: any };
  '/api/v1/tenants': { method: 'POST', body: any, response: any };
  '/api/v1/conversations': { method: 'POST', body: any, response: any };
  '/api/v1/knowledge-bases': { method: 'POST', body: any, response: any };
  '/api/v1/agents': { method: 'GET', body: null, response: AgentDefinition[] };
}