/* eslint-disable @typescript-eslint/no-explicit-any */
// Autogenerated from FastAPI OpenAPI schema. Do NOT manually edit.

export interface AddMessageRequest {
  role: string;
  content: string;
}

export interface AgentDefinition {
  agent_id: string;
  name: string;
  description: string;
  prompt_ref: string;
  allowed_providers?: any[];
  allowed_tools?: any[];
  workflows?: any;
  memory_policy?: any;
  execution_policy?: any;
}

export interface Body_upload_knowledge_document_api_v1_knowledge_bases__id__documents_post {
  file: string;
  chunk_strategy?: string;
}

export interface CompilePromptRequest {
  namespace?: string;
  name: string;
  variables?: any;
  tenant_id?: any;
}

export interface CreateAgentRequest {
  name: string;
  description: string;
  prompt_ref?: string;
  allowed_tools?: any[];
}

export interface CreateConversationRequest {
  metadata?: any;
}

export interface CreateKnowledgeBaseRequest {
  name: string;
}

export interface DocumentQueryRequest {
  query: string;
  limit?: number;
  similarity_threshold?: number;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface PromptDiffRequest {
  text_a: string;
  text_b: string;
}

export interface ValidationError {
  loc: any[];
  msg: string;
  type: string;
  input?: any;
  ctx?: any;
}

export interface WorkflowDefinition {
  workflow_id: string;
  name: string;
  description: string;
  entry_node: string;
  execution_policy?: any;
  memory_policy?: any;
  allowed_tools?: any[];
}
